---
- hosts: "{{ host }}"
  vars:
    http_port: 80
    gather_facts: true
    become: "{{ input }}"
  tasks:
  - name: ensure apache is at the latest version
    yum:
      name: httpd
      state: latest
